export const QUERY_KEYS = {
  CATEGORY: "category",
  CATEGORY_ALL: "category-all",
  CATEGORY_BY_ID: "category-by-id",
  CATEGORY_GROUP: "category-group",
  CATEGORY_GROUP_ALL: "category-group-all",
  CATEGORY_GROUP_BY_ID: "category-group-by-id",
  COLORS: "colors",
  COLORS_ALL: "colors-all",
  COLOR_BY_ID: "color-by-id",
  MENU: "menu",
  MENU_ALL: "menu-all",
  MENU_BY_ID: "menu-by-id",
  PRODUCTS: "products",
  PRODUCT_ALL: "product-all",
  PRODUCT_BY_ID: "product-by-id",
  SIZES: "sizes",
  SIZES_ALL: "sizes-all",
  SIZE_BY_ID: "size-by-id",
  ORDERS: "orders",
  ORDER_BY_ID: "order-by-id",
};
