export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
  },
  CATEGORY_GROUP: {
    GET_ALL: "/admin/category-group",
    GET_BY_ID: "/admin/category-group/:id",
    CREATE: "/admin/category-group",
    UPDATE: "/admin/category-group/:id",
    DELETE: "/admin/category-group/:id",
    BULK_DELETE: "/admin/category-group/bulk-delete",
  },
  CATEGORY: {
    GET_ALL: "/admin/categories",
    GET_BY_ID: "/admin/categories/:id",
    CREATE: "/admin/categories",
    UPDATE: "/admin/categories/:id",
    DELETE: "/admin/categories/:id",
    BULK_DELETE: "/admin/categories/bulk-delete",
  },
  COLOR: {
    GET_ALL: "/admin/colors",
    GET_BY_ID: "/admin/colors/:id",
    CREATE: "/admin/colors",
    UPDATE: "/admin/colors/:id",
    DELETE: "/admin/colors/:id",
    BULK_DELETE: "/admin/colors/bulk-delete",
  },
  MENU: {
    GET_ALL: "/menu",
    GET_BY_ID: "/menu/:id",
    CREATE: "/menu",
    UPDATE: "/menu/:id",
    DELETE: "/menu/:id",
    BULK_DELETE: "/menu/bulk-delete",
  },
  PRODUCT: {
    GET_ALL: "/admin/product",
    GET_BY_ID: "/admin/product/:id",
    CREATE: "/admin/product",
    UPDATE: "/admin/product/:id",
    DELETE: "/admin/product/:id",
    BULK_DELETE: "/admin/product/bulk-delete",
  },
  ORDER: {
    GET_ALL: "/admin/order",
    GET_BY_ID: "/admin/order/:id",
    UPDATE: "/admin/order/:id",
  },
  SIZE: {
    GET_ALL: "/admin/sizes",
    GET_BY_ID: "/admin/sizes/:id",
    CREATE: "/admin/sizes",
    UPDATE: "/admin/sizes/:id",
    DELETE: "/admin/sizes/:id",
    BULK_DELETE: "/admin/sizes/bulk-delete",
  },
  UPLOAD: {
    UPLOAD: "/upload",
    DELETE: "/upload/:id",
  },
};
